### ISSUE TITLE
Restrict the abilities of temporary administrators

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#512]
In light of recent events, Ricky and I strongly feel that temporary administrators should only  have abilities that they need to moderate the server in absence of the crew, which mostly comes down to muting, jailing, kicking, and banning.

Similar to /p (give/take)admin, I propose disabling the following commands for temporary administrators:

1. /house (They shouldn't be able to mess with this. If they want a new location to be added, they should ask existing crew members).
2. /property (The admin command, for the same reasons above). I don't like the idea of them messing with any property settings or the layout. The /properties list is obviously fine.
3. /p hide
4. /p cash [amount] (to prevent setting of values); /p cash for viewing purposes is fine.
5. /p deathmessage [deathmessage] (to prevent editing); /p deathmessage for viewing purposes is fine.
6. /v delete & /v save
7. Prevent them from entering players' houses if players have disabled visitors.

If they want to have fun, they can do so in the presence of (and with the help of) existing crew members who decide to grant them rights solely for fun. I feel we've been pretty lax with this stuff over the years and it's time for a revamp.

**Comment by Specifer** [comment]
However sorry **Beaner** , I feel that this is a little out of the box . The Purpose of temping people that it is to be a good administrator in the future . whats the point of restricting these commands if they wouldn't stop messing with things playfully and whats the point of temping them even . i think it is good already because there was a lot of time where the crew had disappeared and the temps were there to help the players in creating houses , properties etc .. However i haven't seen any complaints linked to temporary administrators deleting a house cause the player was banned especially for Grenading . i just think its good if they don't mess with those in the future instead of changing the restriction for this one temp ? Plus we need someone patient for being temped don't you think ? Everyone makes mistakes i understand but i think its something the crew must make decisions on .

**Comment by Specifer** [comment]
Due to this . I was convinced to bring a new position called Mod where it is lesser than Admin position and were what you said could be implemented as Mod itself . and after it is brought , Admins can only Temp-mod players but cant Temp-admin them . Peter had said the mod was there before but they had removed it since it was not required . if you're request is to be implemented i think it should be implemented as new position ( just my views on this ) but idk what the crew thinks of this .

**Comment by SophiaLVP** [comment]
Yes, I think this is necessary Beaner. I hope our developer respond soon and look into this issue.

**Comment by BeanerLVP** [comment]
> 
> 
> However sorry **Beaner** , I feel that this is a little out of the box . The Purpose of temping people that it is to be a good administrator in the future . whats the point of restricting these commands if they wouldn't stop messing with things playfully and whats the point of temping them even . i think it is good already because there was a lot of time where the crew had disappeared and the temps were there to help the players in creating houses , properties etc .. However i haven't seen any complaints linked to temporary administrators deleting a house cause the player was banned especially for Grenading . i just think its good if they don't mess with those in the future instead of changing the restriction for this one temp ? Plus we need someone patient for being temped don't you think ? Everyone makes mistakes i understand but i think its something the crew must make decisions on .

Sorry, I strongly disagree. Messing around doesn't make anyone a good administrator. I used to be given temp mod rights which were sufficient for fulfilling the primary purpose: watching out for hackers and/or abusing in DM. Temporary crew members are volunteers, nobody forces them to do what they do. Potential candidates can play with stuff and discuss important changes with the crew once they earn their promotion. I know this is a game, but I've observed far too many screw ups over the years; some which even lead me to resign back in 2014. 

Temporary crew members should **not** be able to modify our properties, houses, and vehicle layouts.

**Comment by Specifer** [comment]
Ok , I accept you have a good right point . But what about these points " it is good already because there was a lot of time where the crew had disappeared and the temps were there to help the players in creating houses , properties etc " . Maybe vehicle layout reset can be removed but the above line ?

**Comment by RussellLVP** [comment]
I agree with limiting (1), (2), (5) and (6), but not with the other points.

My main reason for that is that those three commands impose changes that outlast the scope of their temporary rights, and that additional context and understanding is necessary in order to make a judgement on whether it's the right thing to do. Our crew forums are invaluable for that.

Regarding the other points, to me this comes down to trust: a person granted temporary rights must be trusted by those granting said rights. There are very fair reasons why an administrator might have to do either (3), (4) or (7) in a regular session, and restricting those would needlessly limit them. If a person with temporary rights breaks that trust, a note should be added to their record instead.

Regarding a moderator position, no, we will not introduce that again.

**Comment by RickyLVP** [comment]
IMO adding another rank like moderator, even if its just for the purposes for granting temp. rights would be a better option since it gives us more flexibility on weather we want that player to have more access or not. We would like them to learn those command, though not immediately but sometime down the road. If we do not want to have another rank, then maybe a system to enable/disable certain commands for temps, similar to /lvp access.

**Comment by Specifer** [comment]
Perhaps if you want to succeed in restriction just limit certain commands but not the whole command like for example : /house . We could just limit them to only being able to create only , if needed to be deleted only a crew member would be able to do it . But What I am saying is Temp is a position which is equal to administrators . So why grant them if you clearly know that they have been abusing it a lot . This has been there idk ages but now because of this one person's abuse you want to restrict it so that you can temp those type of persons again ? 
Furthermore it's just like if a person damages the house , this is like demolishing the whole construction for that person . So if you don't trust that person enough to give temp rights and go . Please don't , since I would say this is not a priority until NuwaniJs is finished .

**Comment by RussellLVP** [comment]
I have implemented the restrictions for `/house`, `/property`, `/ p deathmessage` and `/ v delete/save` in the following commit, since we have consensus on them:

https://github.com/LVPlayground/playground/commit/588884986ff08f561e6ecc256435818915a3636d

@RickyLVP We could certainly make this configurable, but that might be over-engineering it a bit. I've added infrastructure to the `CommandBuilder` that makes it super easy for us to disable particular commands for temporary administrators.

To repeat, we are not going to introduce a moderator rank again. That simply is not worth the effort. It took ~weeks to remove it from the code many years ago, properly re-introducing that, considering which commands should be available and to whom, thinking about policies on expectations and differences between administrators and moderators and so on is a task we don't have bandwidth for.

@Specifer That's a fair thought, however, we need to consider the practicalities: suppose I create a house for a player and it's _slightly_ too much to the right. With the partial restriction, there would now be a problem that the temp can't fix, and the player would be annoyed because their house is in the wrong spot.

In practice we grant temp rights to people who've shown good judgement and are on the path towards becoming an actual administrator. That's why I'm hesitant towards introducing many restrictions, because they're doing us a favour and we do trust them. Some functions, like the one I outlined earlier, can have impact beyond the scope of their temporary rights, cause awkward situations to arise, or simply require a more thorough understanding of our policies.

Thank you for participating in these discussions!

**Comment by Specifer** [comment]
Cool Russell , But I have to admit that was a very quick,  scripting it . 
@RussellLVP Then crew member should be able to fix it maybe (about /house ), look all I'm saying is a person to be temped should show an upright behaviour , clear judgement and tending towards the right of things . We wouldn't want players temped who just made their way to lvp and they still have a lot of things to learn . And I was annoyed by this pm enable thing even to temp . Could you fix that Russell cause this temp always interfered in others PM's with no reason at all .

**Comment by RussellLVP** [comment]
We cannot expect people to show good judgement if we haven't given them the context necessary to make that judgement. That's what I mean in regards to `/house` and `/property`: thoughts on _where_ and _how_ houses and properties should be placed in the world are depending on a lot of knowledge that's only accessible to permanent administrators.

I don't know what you mean with "pm enable thing". If it's an issue orthogonal to @BeanerLVP's request here, would you please mind filing another issue?

**Comment by Specifer** [comment]
Temporary admins being able to see others PM's I mean . Could you maybe disable it with this issue alongside too , cause it's a bit revealing privacy of others to a temp isn't a good thing

**Comment by RussellLVP** [comment]
I don't see why that wouldn't be a reasonable thing for temporary administrators to access. Players discussing ideas and plans are a very useful and important tool when administrating a server. Taking that privilege seriously is part of the expectations of getting temporary rights.

**Comment by Specifer** [comment]
Well if you say so . But I see it's been misused to get into others conversations for things they are not part of . If simple things like houses and properties are abused . Then a big problematic messages could be used to stir up trouble right ? I think that's why we're restricting settings . For one players continuous abuse ? So I think why shouldn't we disable pm reading too ?

**Comment by RussellLVP** [comment]
Could you please define what you mean with "misused", and what evidence there is to support that?

There are a lot of hypothetical _what ifs_, and we neither can nor want to capture all of them. Instead, we want to err on the side of trusting those we see potential in, and focus on giving them all the tool they could _reasonably_ need to do their duties. Individual people breaking that trust is an issue we cannot address through technology.

**Comment by Specifer** [comment]
I don't have evidence nor am I planning to accuse someone . It's all good if you think pming is right for temp admin , it's just that simple restrictions are made and disable pm readability makes it perfect for learning till they join the crew . And when are trusted for sure , they ll be able to see PM's  and use all commands . Well that's what I thought , if there isn't going to be reply from anyone and all is good . I think it's time to close this issue 😁.

**Comment by SophiaLVP** [comment]
I like the changes. Good job team

**Comment by RussellLVP** [comment]
Hi Beaner - are you satisfied with the changes here? Can we close this Issue?

**Comment by BeanerLVP** [comment]
I don't think this needs to be said, but please ensure /p giveadmin & /p takeadmin are still disabled for temporary crew. Other than that, yes, let's close this issue. Thank you for making the necessary changes!

**Comment by RussellLVP** [comment]
Understood, thank you! Closing this.
